services:
  maps:
    image: maps:local
    container_name: maps-local
    deploy:
      resources:
        limits:
          memory: 100m
        reservations:
          memory: 100m
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    labels:
      log_category: "nginx"